// Hover explanations for every label of the application: page links, card titles, headline figures,
// table columns, legends, badges, buttons and sections. Keys are the visible text with section
// references, counts and dates removed (see keyOf in src/ui/annotate.js). Section numbers refer to
// Phoenix Economics Solutions.

export const PAGES = {
  overview: 'Today’s picture: contract states across economies, inflation with and without Phoenix, priority alerts and the daily market drivers.',
  detect: 'Excess deposits of households, firms and governments from the financial accounts, against the historical threshold S_crit (§3.2–3.3).',
  simulate: 'Run the coupled model on today’s data or a scenario, change any parameter and compare with the no-Phoenix counterfactual (§4, §7).',
  redistribute: 'Where released liquidity goes: credits, wallets, routing between economies of one currency area, spending and recall (§4.5–4.7).',
  contracts: 'Contract state of every economy and the signed, publicly anchored audit ledger (§4.3, §9.4).',
  forecast: 'Twelve-month inflation projections and the probability of touching the trigger, by economy (§6).',
  stability: 'Feedback field, activation and disorder: whether the control loop settles (§4.11–4.12, §8).',
  pilot: 'Plan the randomised trial that would measure the behavioural parameters: sample, power and cost (§10).',
  framework: 'The twelve objectives, the model’s equations, every parameter with its provenance, and interactive explorers (§4).',
  governance: 'Legal basis, monetary accounting of each flow, conversion modes, the mandate-holder and privacy (§2, §9).',
  validate: 'The paper’s published results, their reproduction in this browser, and the risk register (§5–7, §9.6, §11).',
  data: 'Every data source, when it was last refreshed, and the mirrors that keep the app running (§3.1).',
  guide: 'Install the app, a quick start, keyboard shortcuts and answers to common questions.',
};

export const PAGE_LABELS = {
  Overview: 'overview', 'Surplus radar': 'detect', 'Simulation lab': 'simulate', Redistribution: 'redistribute', 'Contracts & audit': 'contracts',
  'Early warning': 'forecast', Stability: 'stability', 'Pilot planner': 'pilot', Framework: 'framework', 'Design & governance': 'governance',
  Evidence: 'validate', 'Data & status': 'data', 'Guide & install': 'guide', Surplus: 'detect', Simulation: 'simulate', Contracts: 'contracts',
};

export const STATES = {
  Active: 'Inflation is above the trigger and excess deposits are above their historical threshold: contracts absorb (§4.3).',
  Armed: 'One of the two conditions holds. Below the threshold nothing is absorbed; just below the trigger the smooth switch allows a small activation (§4.3).',
  Watch: 'The forecast shows a rising probability of breaching the trigger: monitored in advance (§6).',
  Dormant: 'Within bounds: no intervention.',
  Clear: 'No breach expected and the stock is below its threshold.',
  'Pre-empt now': 'Breach likely within twelve months with an exceptional stock: contracts would be prepared in advance (§6).',
  Live: 'Fetched from the publisher in this session.',
  'Refreshing…': 'Being fetched from the publisher now.',
  Snapshot: 'From the hourly baseline snapshot, because browsers cannot fetch this source directly or it has not refreshed yet (§3.1).',
  Stored: 'Stored on this device from an earlier visit; used offline.',
  'Stale (refresh failed)': 'The publisher could not be reached or sent implausible data; the previous copy is kept (§3.1).',
  Unavailable: 'No copy of this source is available yet; the pages that need it say so.',
  Waiting: 'Queued to be fetched from the publisher.',
  'Feasible with bank partners': 'The required sample can be recruited through a few large partner banks (§10.2).',
  Removed: 'The method eliminates this risk (§11).',
  Bounded: 'Measured, bounded and disclosed, with the step that resolves it (§11).',
};

export const TIPS = {
  // ---- card titles
  'The Phoenix closed loop, now': 'The detect → activate → absorb → convert → route → stabilise → feedback loop, with today’s values at each stage (§4).',
  'European monitor': 'Contract state, inflation, stock against threshold or breach probability for each economy. Choose the measure above; select an economy for its details.',
  'Inflation outlook: with and without Phoenix': 'Weighted inflation over the horizon with Phoenix and in the no-Phoenix counterfactual; the gap between the lines is Phoenix’s effect (§7).',
  'Priority alerts': 'Economies where contracts are active, armed or on watch, most urgent first.',
  'Daily drivers': 'Market prices that move the daily inflation nowcast and the policy path between monthly releases (§3.7, §4.10).',
  'Excess deposits by economy and sector': 'Deposits acquired since 2020 above the 2016–2019 pace, by sector; the tick marks S_crit, the historical threshold (§3.2–3.3).',
  'Surplus pressure map': 'Excess stock as a multiple of S_crit: above 1× the stock is exceptional by the standards of pre-2020 history (§3.3).',
  'Measurement choices': 'Change how the excess and its threshold are measured; every page updates (§3.2–3.3, §7.5).',
  'Surplus breaches': 'Economies whose excess stock exceeds S_crit (§3.3).',
  Scenario: 'Starting point of the simulation: today’s data, a reference case from the paper, or a stress scenario (§7).',
  Parameters: 'Every model parameter, grouped by equation. Tags show where each value comes from; hover a parameter for its meaning.',
  Playback: 'Step through the simulated months on the map.',
  'Inflation π': 'Weighted headline inflation with and without Phoenix (§4.9).',
  'Output gap x': 'Output relative to potential, %: negative means slack (§4.8).',
  'Policy rate i': 'The central bank’s rate: market forward path plus a Taylor response to Phoenix’s own effect (§4.10).',
  'Excess deposits S': 'Excess stock with and without Phoenix, against its threshold S_crit (§4.2).',
  'Absorption Φ': 'Funds converted into PHX each month (§4.4).',
  'PHX credits and wallets': 'Absorbed funds held as credits until inflation is back at target, then released into wallets (§4.5–4.6).',
  'Activation Θ': 'How strongly contracts are engaged, from 0 to 1 (§4.3).',
  'Disorder index 𝒟': 'Squared inflation gap plus a quarter of the squared output gap: lower is calmer (§4.12).',
  'Feedback field F': 'The optional feedback law that strengthens absorption when inflation accelerates; off by default (§4.11).',
  'Policy regimes compared': 'The same scenario under alternative designs, one change at a time (§7.4).',
  'Policy optimiser': 'Which economies would still hold an exceptional stock at the end of the horizon, the smallest absorption speed k_A that brings each down to its own S_crit, and what stops the others (§4.3–4.4, §7.6).',
  'Stress test': 'Many runs with correlated parameter draws and alternative model structures: the spread of Phoenix’s effect (§7.7).',
  'Contract events': 'Activations, stand-downs, recalls and mode changes in this run; each can be written to the audit ledger (§9.4).',
  'Routing kernel now': 'Share of each economy’s exported wallet liquidity going to each other economy, from distance, need and inflation (§4.6).',
  'Largest liquidity corridors': 'The biggest flows of wallet liquidity between economies in the simulation (§4.6).',
  'Wallet liquidity at month': 'Spendable PHX wallet balances by economy at that month (§4.6).',
  'Overheating gauges': 'Wallet balances against capacity: above the saturation threshold H* balances are recalled (§4.7).',
  'Routing explorer': 'Pick a source and a target economy to see why liquidity is or is not routed between them (§4.6).',
  'Contract board': 'Every economy’s contract state with its inflation against the trigger and its stock against S_crit (§4.3).',
  'Trigger thresholds': 'The programmable levers of the contracts: trigger, switch, threshold and decay (§4.3, Table 6).',
  'Audit ledger': 'Signed, hash-chained record of every contract event, anchored in the public Sigstore Rekor log (§9.4).',
  'Projected inflation, highest-risk economies': 'Twelve-month projections with the 10th–90th percentile band, for the economies most likely to breach (§6.1).',
  'Breach-risk ranking': 'Economies sorted by the probability that inflation touches the trigger within twelve months (§6.1).',
  'Feedback field F(t) and activation Θ(t)': 'How the feedback field and activation evolve in the current run (§4.3, §4.11).',
  'Observed inflation dispersion': 'Spread of inflation across economies over time: wider means less synchronised (§8).',
  'Disorder by economy at month': 'Disorder index by economy at the end of the horizon with Phoenix, highest first (§4.12).',
  'Design settings': 'Assumptions of the household trial; the sample and power update as you change them (§10.2).',
  'Power by sample size': 'Probability of detecting the effect δ as the number of households grows; the marker shows this design (§10.2).',
  'Strata and allocation': 'Economies eligible for the trial — inflation near or above the trigger, or an exceptional stock — with households allocated by GDP and randomised 1:1 within each (§10.2).',
  'Simulated trial': 'One trial drawn household by household, analysed with the estimator of §10.3.',
  Safeguards: 'Consent, data protection, capital protection and ethics approval (§9.5, §10.5).',
  'Load real trial results': 'Load a CSV of real trial data; the app estimates the forgone-spending rate with the estimator of §10.3.',
  'Objectives and where they are delivered': 'The twelve objectives of Phoenix and the pages that deliver each (Table 1).',
  'Integrated control loop': 'The stages of the loop and the equation behind each (§4).',
  'Excess deposits from the financial accounts': 'Deposits above the 2016–2019 pace held as a share of GDP, by sector (§3.2).',
  'Threshold from history': 'S_crit: the 90th percentile of pre-2020 accumulations of the same length (§3.3).',
  'Inflow decay by sector': 'How fast new excess deposits stop arriving, estimated per sector (§3.4).',
  'Output gap and its monthly update': 'HP-filtered output gap moved monthly by the unemployment surprise times Okun’s coefficient (§3.5).',
  'Daily inflation nowcast': 'Inflation updated every business day from oil prices in euro and the exchange rate (§3.7).',
  'Phillips curve estimated on the EU panel': 'Core inflation’s response to the output gap and energy, estimated with instruments on 27 economies (§5.1).',
  'Early-warning projection': 'Energy base effects plus a core projection reverting to the anchor (§6.1).',
  'Breach probability': 'Share of simulated paths touching the trigger within twelve months (§6.1).',
  'Conservation theorem': 'Every euro absorbed is accounted for: held as credits, in wallets, spent, matured or recalled (§4.13).',
  'Positivity, Lyapunov certificate and input-to-state gain': 'Why the model’s stocks stay non-negative and the core settles (§8).',
  'Randomised trial: estimator and sample size': 'The Wald estimator and the sample-size formula of the trial (§10).',
  'Parameters and provenance': 'Current and default value of every parameter, and whether it is estimated, from the literature, a design choice or to be measured (Table 6).',
  'Absorption response': 'Monthly absorption against the size of the stock, for chosen k_A and floor (§4.4).',
  'Trigger switch': 'Activation against inflation for the smooth switch and the step with hysteresis (§4.3).',
  'Routing reach': 'Routing weight against distance for a chosen reach σ (§4.6).',
  Glossary: 'Definitions of the terms used throughout the app.',
  'Lawful absorption by sector': 'The legal instrument through which each sector’s funds could be absorbed (§2.3).',
  'Monetary accounting of each flow': 'Where each Phoenix flow sits on the balance sheets of the central bank, banks and holders (§9.1).',
  'Conversion modes': 'How absorbed funds are held, released and recalled (§2.2).',
  'Governance: the mandate-holder': 'Who operates Phoenix and how it is held accountable (§9.2).',
  'Privacy and security': 'What data are used, what stays on this device, and how the app is secured (§9.5).',
  'Legal analysis': 'Phoenix against the EU Treaties and case law (§2.5).',
  'Published results': 'The paper’s results, loaded from the archived results file (§9.6).',
  'Reproduce the paper in this browser': 'Runs the paper’s computation on the archived data and compares every published value (§9.6).',
  'Core Phillips curve, EU-27': 'Estimates of reversion a, slope κ and energy pass-through γ_E by estimator (Table 4).',
  'Real-time out-of-sample test': 'Forecast errors using only data available at each date (Table 5).',
  'Early-warning backtest, EU-27': 'Projection and breach-probability scores against benchmarks, 2001–2026 (Table 7).',
  'EU-27 as of 31 December 2021, with and without Phoenix': 'The last surge on the data published by then (Table 11).',
  'Validation from November 2021': 'The model’s no-Phoenix paths against actual inflation (Figure 5).',
  'Live results by region, 24 months': 'Phoenix’s effect on today’s archived data, by region (Table 9).',
  'Stress tests': 'Distribution of the effect under correlated parameter draws and four model structures (§7.7).',
  'Risk register': 'Every methodological risk, how it is removed or bounded, and the step that resolves it (Table 20).',
  'Live sources': 'Each data series, its publisher, cadence and when it was last retrieved (§3.1).',
  Resilience: 'How the app keeps working when a publisher or host is down (§3.1).',
  Mirrors: 'Independent hosts serving the app and its data.',
  'Install Phoenix': 'Install the app on this device to use it offline.',
  'Quick start': 'The fastest way through the app.',
  Shortcuts: 'Keyboard shortcuts.',
  Questions: 'Answers to common questions.',
  'Network domain': 'Economies as nodes of a graph weighted by distance; diffusion becomes the graph Laplacian (§4.1).',

  // ---- headline figures
  'Weighted inflation': 'GDP-weighted headline inflation of the selected region, updated daily by the nowcast between monthly releases (§3.7).',
  'Excess deposits': 'Deposits acquired since 2020 above the 2016–2019 pace, all sectors (§3.2).',
  'Eurosystem deposit facility': 'Money banks hold overnight at the Eurosystem: the existing absorption of excess liquidity (§2.3).',
  'Output gap and policy rate': 'Output relative to potential and the central bank’s rate today (§3.5, §4.10).',
  'Absorbed in 24 months': 'Funds Phoenix would convert into PHX over two years in the current run (§4.4).',
  'Brent crude in €': 'Oil price in euro: drives the daily nowcast and energy inflation (§3.7).',
  'EUR / USD': 'Euro exchange rate: drives the nowcast’s exchange-rate term for euro-area members (§3.7).',
  '€STR overnight rate': 'The euro short-term rate: today’s money-market rate.',
  '10-year AAA yield': 'Euro-area AAA government bond yield at ten years: the long-rate market signal.',
  'Excess deposits Σλₖ·Sᵏ': 'Weighted sum of the sectors’ excess deposits (§4.2).',
  Government: 'General government (§3.2).',
  Corporate: 'Non-financial corporations (§3.2).',
  Household: 'Households and non-profit institutions serving them (§3.2).',
  'Inflation at m24': 'Weighted inflation at month 24 with Phoenix, and the difference from the no-Phoenix run.',
  'Policy rate at m24': 'Policy rate at month 24 and its difference from the no-Phoenix run (§4.10).',
  'Excess stock absorbed': 'Share of the starting excess converted into PHX over the horizon (§4.4).',
  'Months until inflation stays within ±0.3 pp of target': 'When inflation settles near target, with and without Phoenix.',
  'Disorder index at m24': 'Squared inflation gap plus a quarter of the squared output gap at month 24 (§4.12).',
  'Conservation check': 'Largest gap between money absorbed and money accounted for; zero up to rounding (§4.13).',
  'Converted to PHX credits': 'Funds absorbed and held as credits (§4.5).',
  'Released into wallets': 'Credits released into spendable wallets once inflation is back at target (§4.5).',
  'Routed between economies': 'Wallet liquidity moved from overheating economies to those with room (§4.6).',
  'Spent into real economy': 'Wallet balances spent by holders (§4.6).',
  'Recalled to Digital Euro': 'Saturated wallet balances moved into Digital Euro holdings (§4.7).',
  'Swept to bank accounts': 'Recalled balances above Digital Euro capacity returned to bank accounts (§4.7).',
  'Recalled to Dragon reserve': 'Balances recalled in crisis mode, when inflation exceeds the crisis level (§4.7).',
  'Likely to activate within 12 months': 'Economies with breach probability of at least 50% and an exceptional stock (§6.1).',
  'On watch': 'Economies with breach probability of at least 25% or an exceptional stock (§6.1).',
  'Next projected trigger': 'The earliest month in which an economy’s projection reaches the trigger (§6.1).',
  'Output gap at m24': 'Output relative to potential at month 24 (§4.8).',
  'Live inflation dispersion': 'Standard deviation of inflation across economies today.',
  'Recall activity': 'Wallet balances recalled in the current run (§4.7).',
  'Households per arm': 'Households needed in each of the treatment and control groups (§10.2).',
  'Detectable δ with this sample': 'Smallest forgone-spending rate the trial detects with 80% power (§10.2).',
  'Trial cost': 'Premium, data and operations, and encouragement costs (Table 18).',
  'Funds placed in wallets': 'Money households in the trial are expected to place (Table 18).',
  'If δ is as hypothesised': 'What the hypothesised forgone-spending rate would mean for inflation in the 2021 scenario (§10.3).',
  'Existing absorption: ECB deposit facility': 'Banks’ overnight deposits at the Eurosystem, which already absorb liquidity (§2.3).',
  'What Phoenix adds': 'Voluntary absorption from households, firms and governments under a cap (§2).',
  'Direct government financing': 'Prohibited by Art. 123 TFEU; Phoenix never lends to governments (§2.5).',
  'Phillips slope κ (IV), live data': 'The slope re-estimated on today’s data, against the paper’s value (§5.1).',
  'Threshold S_crit, live data': 'The historical threshold recomputed on today’s data (§3.3).',
  'Conservation, current run': 'Money-conservation residual of the current run (§4.13).',

  // ---- table columns
  Regime: 'The design variant simulated (§7.4).',
  'π at m24': 'Weighted inflation at month 24, %.',
  'Δπ vs no Phoenix, pp': 'Phoenix’s effect on inflation: with minus without, percentage points.',
  'Excess stock at m24': 'Excess deposits remaining at month 24.',
  Absorbed: 'Funds converted into PHX over the horizon.',
  'Disorder at m24': 'Disorder index at month 24 (§4.12).',
  Month: 'Month of the simulation.',
  Economy: 'Economy concerned.',
  Event: 'What happened.',
  Cause: 'The condition that caused it.',
  State: 'Contract state (§4.3).',
  Inflation: 'Latest headline inflation, %, official or nowcast (§3.7).',
  'vs trigger': 'Inflation minus the trigger, points.',
  'S / S_crit': 'Excess stock as a multiple of its historical threshold (§3.3).',
  'Θ* activation': 'Activation contracts would reach in steady state under current conditions (§4.3).',
  'P(breach 12 m)': 'Probability that inflation touches the trigger within twelve months (§6.1).',
  Signal: 'Early-warning status (§6).',
  Trend: 'Inflation over the last two years.',
  Now: 'Latest inflation, %.',
  '+6 m': 'Projected inflation six months ahead, %.',
  '+12 m': 'Projected inflation twelve months ahead, %.',
  'IMF next year': 'The IMF’s World Economic Outlook projection for next year, %.',
  'P(breach)': 'Probability of touching the trigger within twelve months (§6.1).',
  'Trigger in': 'Months until the projection reaches the trigger.',
  'S/S_crit now → next year': 'Stock against threshold today and projected a year ahead (§3.4).',
  Quantity: 'Item of the trial budget.',
  Value: 'Amount.',
  Group: 'Equation group the parameter belongs to.',
  Parameter: 'Model parameter.',
  Current: 'Value in use now.',
  Default: 'The paper’s value (Table 6).',
  Provenance: 'Estimated from data, from the literature, a policy choice, to be measured, or numerical (Table 6).',
  Sector: 'Institutional sector.',
  'Absorption mechanism': 'Instrument through which funds are absorbed.',
  'Legal basis': 'The legal provision that allows it.',
  Flow: 'Phoenix flow.',
  Effect: 'Effect on balance sheets and money.',
  Note: 'Remarks.',
  Question: 'Legal question.',
  Assessment: 'The paper’s assessment.',
  Estimator: 'Estimation method (§5.1).',
  Sample: 'Years used.',
  a: 'Annual reversion of core inflation to its anchor (§5.1).',
  'κ': 'Phillips slope: core inflation’s response to the output gap, per year (§5.1).',
  'γ_E': 'Pass-through of energy inflation to core inflation (§5.1).',
  'First-stage F': 'Strength of the instruments; above 10 is strong (§5.1).',
  'Model given energy': 'Forecast error of the model when that year’s energy inflation is known (Table 5).',
  'Benchmark given energy': 'Error of the fair benchmark given the same energy information (Table 5).',
  'Model, mean energy': 'Model error with energy inflation at its mean (Table 5).',
  'No change': 'Error of assuming inflation stays where it is.',
  Measure: 'Score reported.',
  'All, 2001–2026': 'All forecast origins.',
  'Hold-out, 2001–2017': 'Origins not examined while the method was chosen: the clean test (§6.1).',
  'Recent, 2018–2026': 'Recent origins, including the 2021–2023 surge.',
  'π with, %': 'Inflation with Phoenix, %.',
  'Δπ': 'Phoenix’s effect on inflation, thousandths of a point.',
  'S with / without, €bn': 'Excess stock with and without Phoenix.',
  'S_crit, €bn': 'Historical threshold in euro.',
  'Credits, €bn': 'PHX credits held.',
  'Wallets, €bn': 'PHX wallet balances.',
  'Euro area': 'The euro-area members.',
  'European Union': 'The 27 EU members.',
  Global: 'The 29-economy global panel (§3.8).',
  '10th percentile': 'One run in ten gives a smaller value.',
  Median: 'Half the runs give less, half more.',
  '90th percentile': 'One run in ten gives a larger value.',
  'Largest conservation residual, €bn': 'Largest money-accounting gap across all runs; zero up to rounding (§4.13).',
  'No.': 'Number in Table 20.',
  Risk: 'What could make a result misleading.',
  Treatment: 'How the paper deals with it.',
  Status: 'Removed by the method, or bounded and disclosed.',
  Where: 'Section of the paper.',
  Resolution: 'The step that resolves a bounded risk.',
  Source: 'Data series.',
  Publisher: 'Official publisher.',
  'Release cadence': 'How often the publisher releases new data.',
  Retrieved: 'When this app last obtained it.',
  'Publisher update (where reported)': 'When the publisher last updated the series.',

  // ---- legends
  'With Phoenix': 'Path with Phoenix engaged.',
  'Without Phoenix': 'Counterfactual path without Phoenix.',
  Without: 'Counterfactual path without Phoenix.',
  'S_crit': 'Historical threshold of exceptional excess (§3.3).',
  'Credits C': 'Absorbed funds held as PHX credits (§4.5).',
  'Wallets L': 'Spendable PHX wallet balances (§4.6).',
  F: 'Feedback field (§4.11).',
  'Θ': 'Activation, 0 to 1 (§4.3).',
  Sigmoid: 'Smooth switch: activation rises gradually around the trigger.',
  'Step, rising': 'Step switch as inflation rises: on at the trigger.',
  'Step, falling': 'Step switch as inflation falls: off only below the trigger minus the hysteresis band.',
  Actual: 'Published EU-27 inflation.',
  'Model, realised energy': 'Model with the policy rates set and the energy prices that occurred.',
  'Model, ex ante': 'Model with the forward rates and energy prices known in November 2021.',

  // ---- buttons and choices
  'Contract state': 'Colour economies by contract state.',
  'Surplus / S_crit': 'Colour economies by excess stock against threshold.',
  'Breach probability': 'Colour economies by twelve-month breach probability.',
  'Open lab': 'Open the Simulation lab with this scenario.',
  Table: 'Show the numbers behind the chart as a table.',
  'S/S_crit': 'Show the stock as a multiple of its threshold.',
  '€bn': 'Show the stock in euro billions.',
  'Log to ledger': 'Write this run’s contract events to the audit ledger (§9.4).',
  CSV: 'Download the simulation results as CSV.',
  Reset: 'Restore every parameter to the paper’s value.',
  Play: 'Animate the simulation month by month.',
  'Optimise k_A': 'Find the smallest absorption speed that brings every economy that can be reached down to its own S_crit by the end of the horizon (§7.6).',
  'Search again': 'Repeat the k_A search with the current settings and data.',
  'Searching…': 'The search is running: about 14 simulations of the whole region, a few seconds.',
  'Run stress test': 'Run many simulations with correlated parameter draws (§7.7).',
  Detail: 'Open this economy’s details.',
  All: 'Show all ledger entries.',
  'Live data': 'Ledger entries from live monitoring.',
  Simulation: 'Ledger entries from simulations.',
  Verify: 'Check every link, hash and signature, and each anchor against Rekor (§9.4).',
  Anchor: 'Publish the chain head to the public transparency log (§9.4).',
  JSON: 'Export the ledger for independent verification.',
  Clear: 'Delete the ledger on this device.',
  'New draw': 'Simulate another trial with fresh random draws.',
  'Pre-register': 'Record the protocol’s hash in the audit ledger before any data are collected (§10.5).',
  Template: 'Download a template for real trial results.',
  Reproduce: 'Recompute the paper’s results here and compare every value (§9.6).',
  'Export data': 'Download the data currently used.',
  'Refresh now': 'Fetch every source from its publisher now, instead of waiting for the automatic refresh every 15 minutes.',
  Protect: 'Ask the browser to keep stored data from being cleared.',
  Run: 'Horizon, time step and on/off switches of the run.',

  // ---- expandable sections
  'How surplus is measured': 'The method behind the excess and its threshold.',
  'How the coupled system is solved': 'How the equations are integrated in time.',
  'How redistribution works': 'The rules behind routing and recall.',
  'Why a hash-chained ledger': 'Why the audit trail cannot be rewritten unnoticed.',
  Method: 'How the projections and probabilities are computed.',
  'Reading the loop': 'How to interpret the stability charts.',
  'Why a household trial': 'Why behaviour must be measured rather than assumed.',
  'Position relative to existing instruments': 'How Phoenix differs from existing central-bank tools.',
  'Show the full register': 'All 55 risks with their treatment and resolution.',
  'How to read this page': 'What each card on this page shows.',
  'How freshness works': 'How data are refreshed and what happens offline.',
};

// Parameter-group headings in the Simulation lab.
export const GROUPS = {
  Measurement: 'How the excess stock and its threshold are measured (§3.2–3.4, §4.2).',
  'Contract activation': 'When and how fast contracts engage (§4.3).',
  'Absorption, credits and premium': 'How much is absorbed, held and paid (§4.4–4.5).',
  'Wallets, routing & recall': 'Where released liquidity goes and when it is recalled (§4.6–4.7).',
  'Demand, inflation & policy rate': 'The macroeconomic core: output gap, Phillips curve and policy rate (§4.8–4.10).',
  'Feedback & loss': 'The optional feedback law and the loss used to judge outcomes (§4.11–4.12, §7.6).',
};
