// Production build: pre-renders equations to MathML, bundles and minifies, writes the
// service worker with a content-hashed precache, PNG icons, and a single-file offline edition.
import { build } from 'esbuild';
import katex from 'katex';
import { Resvg } from '@resvg/resvg-js';
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile, rm, copyFile, readdir } from 'node:fs/promises';
import { EQUATIONS, SUPPORT } from '../src/content/equations.js';

const root = new URL('../', import.meta.url);
const p = rel => new URL(rel, root);
const DIST = p('dist/');
const hash = buf => createHash('sha256').update(buf).digest('hex').slice(0, 10);

// 1. Equations → MathML (no fonts or runtime library needed in the browser).
const math = {};
const render = (tex, display) => katex.renderToString(tex, { output: 'mathml', displayMode: display, throwOnError: false });
for (const e of EQUATIONS) {
  math[e.id] = render(e.tex, true);
  e.rel.forEach((r, i) => { math[`${e.id}-r${i}`] = render(r, false); });
}
for (const e of SUPPORT) math[e.id] = render(e.tex, true);
await mkdir(p('src/generated/'), { recursive: true });
await writeFile(p('src/generated/math.js'), `// Generated by scripts/build.mjs — do not edit.\nexport default ${JSON.stringify(math)};\n`);

// 2. Bundles.
await rm(DIST, { recursive: true, force: true });
await mkdir(p('dist/icons/'), { recursive: true });
await mkdir(p('dist/data/'), { recursive: true });
const common = { bundle: true, minify: true, target: ['es2020'], legalComments: 'none', write: false, format: 'iife' };
const [appB, mcB, reproB, cssB] = await Promise.all([
  build({ ...common, entryPoints: [p('src/main.js').pathname] }),
  build({ ...common, entryPoints: [p('src/workers/montecarlo.js').pathname] }),
  build({ ...common, entryPoints: [p('src/workers/reproduce.js').pathname] }),
  build({ ...common, format: undefined, entryPoints: [p('static/app.css').pathname], loader: { '.css': 'css' } }),
]);
const appJs = appB.outputFiles[0].text, mcJs = mcB.outputFiles[0].text, reproJs = reproB.outputFiles[0].text, css = cssB.outputFiles[0].text;
const bootJs = await readFile(p('static/boot.js'), 'utf8');
const mirrorsCfg = JSON.parse(await readFile(p('mirrors.json'), 'utf8'));
const configJs = `self.PHX_MIRRORS=${JSON.stringify(mirrorsCfg.mirrors)};self.PHX_DATA_ENDPOINTS=${JSON.stringify(mirrorsCfg.dataEndpoints || [])};`;

let snapshot = '{}';
try { snapshot = await readFile(p('public/data/snapshot.json'), 'utf8'); } catch { console.warn('No snapshot found; run npm run snapshot'); }

const files = { 'app.js': appJs, 'mc.js': mcJs, 'repro.js': reproJs, 'app.css': css, 'boot.js': bootJs, 'config.js': configJs };
const v = Object.fromEntries(Object.entries(files).map(([k, c]) => [k, hash(c)]));
for (const [k, c] of Object.entries(files)) await writeFile(p(`dist/${k}`), c);
await writeFile(p('dist/data/snapshot.json'), snapshot);
// The archived data and published results of the paper, for the December 2021 scenario and the
// in-browser reproduction on the Evidence page (§9.6). Data only: documents are never published.
await mkdir(p('dist/data/paper/'), { recursive: true });
const paperFilesRaw = {};
for (const f of ['vintage-2026-10-04.json', 'weo-vintages.json', 'results-2026-10-04.json']) { await copyFile(p(`paper/${f}`), p(`dist/data/paper/${f}`)); paperFilesRaw[f] = (await readFile(p(`paper/${f}`))).length + ':' + hash(await readFile(p(`paper/${f}`))); }
const paperHash = hash(['vintage-2026-10-04.json', 'weo-vintages.json', 'results-2026-10-04.json'].map(f => String(paperFilesRaw[f])).join(''));
const paperFiles = { vintage: await readFile(p('paper/vintage-2026-10-04.json'), 'utf8'), weo: await readFile(p('paper/weo-vintages.json'), 'utf8'), results: await readFile(p('paper/results-2026-10-04.json'), 'utf8') };

// 3. Icons.
const iconSvg = await readFile(p('static/icons/icon.svg'));
const maskSvg = await readFile(p('static/icons/maskable.svg'));
await copyFile(p('static/icons/icon.svg'), p('dist/icons/icon.svg'));
const png = (svg, size) => new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render().asPng();
await writeFile(p('dist/icons/icon-192.png'), png(iconSvg, 192));
await writeFile(p('dist/icons/icon-512.png'), png(iconSvg, 512));
await writeFile(p('dist/icons/maskable-512.png'), png(maskSvg, 512));
await writeFile(p('dist/icons/apple-touch-icon.png'), png(maskSvg, 180));
await writeFile(p('dist/favicon.png'), png(iconSvg, 48));

// 4. Manifest.
const manifest = {
  id: './', name: 'Phoenix Economics — Real-Time Surplus Absorption & Inflation Stabilisation', short_name: 'Phoenix',
  description: 'Live implementation of Phoenix Economics Solutions: measure idle money, trigger lawful contracts, absorb, route and recall liquidity, warn early and audit every step, on official data.',
  start_url: './#/overview', scope: './', display: 'standalone', display_override: ['window-controls-overlay', 'standalone', 'minimal-ui'],
  orientation: 'any', background_color: '#f6f5f1', theme_color: '#c2410c', categories: ['finance', 'education', 'productivity'], lang: 'en',
  icons: [
    { src: 'icons/icon.svg', sizes: 'any', type: 'image/svg+xml' },
    { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    { src: 'icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
  shortcuts: [
    { name: 'Simulation lab', url: './#/simulate', icons: [{ src: 'icons/icon-192.png', sizes: '192x192' }] },
    { name: 'Contracts & audit', url: './#/contracts', icons: [{ src: 'icons/icon-192.png', sizes: '192x192' }] },
    { name: 'Early warning', url: './#/forecast', icons: [{ src: 'icons/icon-192.png', sizes: '192x192' }] },
  ],
};
await writeFile(p('dist/manifest.webmanifest'), JSON.stringify(manifest, null, 1));

// 5. HTML with a strict Content-Security-Policy.
const DATA_ORIGINS = ['https://ec.europa.eu', 'https://data-api.ecb.europa.eu', 'https://api.worldbank.org', 'https://api.db.nomics.world', 'https://api.frankfurter.dev', 'https://bdm.insee.fr', 'https://rekor.sigstore.dev'];
const mirrorOrigins = [...new Set([...mirrorsCfg.mirrors, ...(mirrorsCfg.dataEndpoints || [])].map(m => new URL(m).origin))];
const csp = (scriptSrc, extra = '') => [
  "default-src 'self'", `script-src ${scriptSrc}`, "style-src 'self' 'unsafe-inline'", "img-src 'self' data: blob:", "font-src 'self'",
  `connect-src 'self' ${[...DATA_ORIGINS, ...mirrorOrigins].join(' ')}`, "worker-src 'self' blob:", "manifest-src 'self'",
  "object-src 'none'", "base-uri 'self'", "form-action 'none'", extra,
].filter(Boolean).join('; ');
const head = (cspValue, assets) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta http-equiv="Content-Security-Policy" content="${cspValue}">
<meta name="referrer" content="no-referrer">
<title>Phoenix Economics</title>
<meta name="description" content="${manifest.description}">
<meta name="theme-color" content="#fbfaf7">
<meta name="color-scheme" content="light dark">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Phoenix">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta property="og:title" content="Phoenix Economics">
<meta property="og:description" content="${manifest.description}">
${assets}
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<header id="top"></header>
<div class="layout">
<nav id="nav" aria-label="Main"></nav>
<main id="main" tabindex="-1"><div class="empty"><div class="spinner" aria-hidden="true"></div><p>Starting Phoenix…</p></div></main>
</div>
<nav id="tabs" aria-label="Primary"></nav>
<noscript><p style="padding:16px">Phoenix needs JavaScript to run its models in your browser.</p></noscript>
</body>
</html>
`;
const assets = `<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" href="icons/icon.svg" type="image/svg+xml">
<link rel="icon" href="favicon.png" type="image/png">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<link rel="stylesheet" href="app.css?v=${v['app.css']}">
<script src="boot.js?v=${v['boot.js']}"></script>
<script defer src="config.js?v=${v['config.js']}"></script>
<script defer src="app.js?v=${v['app.js']}"></script>`;
const html = head(csp("'self'"), assets);
await writeFile(p('dist/index.html'), html);
await writeFile(p('dist/404.html'), html);

// 6. Service worker.
const precache = ['./', 'index.html', `app.js?v=${v['app.js']}`, `app.css?v=${v['app.css']}`, `boot.js?v=${v['boot.js']}`, `config.js?v=${v['config.js']}`, 'mc.js', 'repro.js',
  'manifest.webmanifest', 'icons/icon.svg', 'icons/icon-192.png', 'icons/icon-512.png', 'icons/maskable-512.png', 'icons/apple-touch-icon.png', 'favicon.png',
  // The paper's archived data and results, so the December 2021 scenario, the Evidence page and the
  // reproduction work offline.
  'data/paper/results-2026-10-04.json', 'data/paper/weo-vintages.json', 'data/paper/vintage-2026-10-04.json'];
const swTemplate = await readFile(p('static/sw.js'), 'utf8');
// The version depends on code only: hourly data updates reach users through the data route, without a
// new app version, a reinstall or a reload.
const version = hash(Object.values(v).join('') + html + swTemplate + paperHash);
const sw = swTemplate.replace('__VERSION__', version).replace('__PRECACHE__', JSON.stringify(precache));
await writeFile(p('dist/sw.js'), sw);

// 7. Single-file offline edition (open straight from disk, no host required).
const esc = s => s.replace(/<\/script/gi, '<\\/script');
const offlineAssets = `<link rel="icon" href="data:image/svg+xml,${encodeURIComponent(iconSvg.toString())}">
<style>${css}</style>
<script>${esc(bootJs)}</script>
<script>${esc(configJs)}self.PHX_EMBED_SNAPSHOT=${esc(snapshot)};self.PHX_MC_SRC=${esc(JSON.stringify(mcJs))};self.PHX_REPRO_SRC=${esc(JSON.stringify(reproJs))};self.PHX_EMBED_PAPER={vintage:${esc(paperFiles.vintage)},weo:${esc(paperFiles.weo)},results:${esc(paperFiles.results)}};self.PHX_ICON=${JSON.stringify('data:image/svg+xml,' + encodeURIComponent(iconSvg.toString()))};</script>
<script defer src="data:text/javascript;base64,${Buffer.from(appJs).toString('base64')}"></script>`;
const offlineHtml = head(csp("'self' 'unsafe-inline' data:"), offlineAssets);
await writeFile(p('dist/phoenix-offline.html'), offlineHtml);

await writeFile(p('dist/.nojekyll'), '');
await writeFile(p('dist/robots.txt'), 'User-agent: *\nAllow: /\n');
const headers = `/*\n  X-Content-Type-Options: nosniff\n  X-Frame-Options: DENY\n  Referrer-Policy: no-referrer\n  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()\n  Strict-Transport-Security: max-age=63072000; includeSubDomains\n  Cross-Origin-Opener-Policy: same-origin\n/sw.js\n  Cache-Control: no-cache\n/index.html\n  Cache-Control: no-cache\n/data/*\n  Cache-Control: no-cache\n`;
await writeFile(p('dist/_headers'), headers);

// Guard: source documents (.pdf, .docx, .doc) must never be published.
const walk = async dir => (await readdir(dir, { withFileTypes: true })).flatMap(async e => e.isDirectory() ? walk(`${dir}/${e.name}`) : [`${dir}/${e.name}`]);
const allFiles = (await Promise.all(await walk(DIST.pathname.replace(/\/$/, '')))).flat(Infinity);
const banned = allFiles.filter(f => /\.(pdf|docx?|dotx)$/i.test(f));
if (banned.length) { console.error('Refusing to build: document files found in dist:', banned); process.exit(1); }

const sizes = {};
for (const f of await readdir(DIST)) { try { sizes[f] = (await readFile(p(`dist/${f}`))).length; } catch {} }
console.log('built', version, Object.entries(sizes).map(([k, s]) => `${k} ${(s / 1024).toFixed(1)}KB`).join(', '));
